plugin: aws_ec2

aws_access_key: AKIAQJTL7QX2HDZXLWTI
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
