plugin: aws_ec2

aws_access_key: AKIA6PVREJYHONMXU423 
aws_secret_key: 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 

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
